POST http://localhost:8080/auth/login
Content-Type: application/json
Session-Id: sessionId

{
  "username": "lelar",
  "password": "qwerty12345"
}

### register

POST http://localhost:8080/auth/register
Content-Type: application/json
Session-Id: sessionId

{
  "username": "username",
  "firstName": "firstName",
  "secondName": "secondName",
  "patronymic": "patronymic",
  "password": "qwerty12345",
  "birthDate": "1999-10-01T19:42:01"
}

###

POST http://localhost:8080/auth/test
Content-Type: application/json
Session-Id: sessionId

{
  "username": "username",
  "firstName": "firstName",
  "secondName": "secondName",
  "patronymic": "patronymic",
  "password": "jdbc:h2:mem:ee2719e7-7028-41ab-8a62-db40b0d3f389"
}

###

POST http://localhost:8080/tournament/getBetween
Content-Type: application/json

{
  "startBeginDate": "2020-01-01T00:00:00",
  "startEndDate": "2021-11-01T00:00:00",
  "needToLoadPictures": true
}

###

POST http://localhost:8080/tournament/update
Content-Type: application/json
Session-Id: sessionId

{
  "entity": {
    "id": 1,
    "tournamentName": "name",
    "startDate": "2020-10-01T00:00:00",
    "endDate": "2021-10-01T00:00:00",
    "genderType": "M",
    "squadId": 1,
    "opponentSquadId": 2,
    "address": "address"
  }
}

###

POST http://localhost:8080/pictures/getByPath
Content-Type: application/json

{
  "path": "/pictures/image.jpg"
}

###
