spring:
  datasource:
    name: cloud
    username: admin
    password: admin
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG